import com.android.build.api.dsl.LibraryExtension

plugins {
    alias(libs.plugins.android.library)
}

// A ponte com o Core (ADR 0023). Este módulo é o único que compila o que
// `just android/generate` põe em android/generated/: compilar lá e em :app daria classe
// duplicada no dex. `extensions.configure` e não `android {}`: com AGP 9 o acessor de
// biblioteca resolve para a extensão antiga, e `sourceSets` quebra.
extensions.configure<LibraryExtension> {
    namespace = "sh.logn.coreshell"
    compileSdk = 37

    defaultConfig {
        // Tem de ser o min_sdk de shared_core/boltffi.toml.
        minSdk = 26
        consumerProguardFiles("consumer-rules.pro")
        // Tem de ser architectures de shared_core/boltffi.toml.
        ndk { abiFilters += listOf("arm64-v8a", "x86_64") }
        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
    }

    sourceSets.getByName("main") {
        kotlin.directories += listOf(
            "../generated/typegen",
            "../generated/boltffi/kotlin",
            "../generated/localization/java",
        )
        res.directories += "../generated/localization/res"
        jniLibs.directories += "../generated/boltffi/jniLibs"
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    // O .so é carregado direto do APK, sem descompactar.
    packaging { jniLibs.useLegacyPackaging = false }

    lint {
        abortOnError = true
        lintConfig = file("lint.xml")
    }
}

// Build fora do just: para se a fonte do Core ou do catálogo mudou depois do último
// `just android/generate`. Um .so velho com tipos novos troca o índice das variantes de
// bincode, e em release isso aborta no nativo sem nada no log do Java.
val verifyGenerated by tasks.registering {
    val stamp = layout.projectDirectory.file("../generated/STAMP").asFile
    val sources = files(
        fileTree("../../shared_core/src"),
        "../../shared_core/Cargo.lock",
        "../../shared_core/boltffi.toml",
        fileTree("../../i18n"),
    )
    inputs.files(sources)
    doLast {
        check(stamp.exists()) { "rode just android/generate antes do build" }
        val newer = sources.files.filter { it.lastModified() > stamp.lastModified() }
        check(newer.isEmpty()) {
            "a fonte mudou depois do generate (${newer.first()}): rode just android/generate"
        }
    }
}
tasks.named("preBuild") { dependsOn(verifyGenerated) }

dependencies {
    api(libs.kotlinx.coroutines.android)

    testImplementation(libs.junit)
    testImplementation(libs.kotlinx.coroutines.test)
    androidTestImplementation(libs.androidx.test.runner)
    androidTestImplementation(libs.androidx.test.ext.junit)
    androidTestImplementation(libs.kotlinx.coroutines.test)
}
