[package]
name = "shared_core"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib", "cdylib", "rlib"]

[dependencies]
crux_core = "0.20.0"
crux_http = "0.20.0"
crux_macros = "0.10.1"
serde = { version = "1.0", features = ["derive"] }
uniffi = { version = "0.27", features = ["cli"] }


[[bin]]
name = "uniffi-bindgen"
path = "uniffi-bindgen.rs"
