[package]
name = "shared_core"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib", "cdylib", "rlib"]

[dependencies]
crux_core = "0.3"
crux_http = "0.3"
crux_macros = "0.3"
serde = { version = "1.0", features = ["derive"] }
uniffi = "0.27"

[build-dependencies]
uniffi = { version = "0.27", features = ["build"] }
