name: LogNiOS
options:
  bundleIdPrefix: sh.logn
  deploymentTarget:
    iOS: '16.0'
packages:
  LogNCoreFFI:
    path: ../LogNCoreFFI
  App:
    path: ../SharedCore/App
  PostHog:
    url: https://github.com/PostHog/posthog-ios.git
    from: 3.0.0
targets:
  LogNiOS:
    type: application
    platform: iOS
    deploymentTarget: '16.0'
    bundleId: sh.logn.app

    sources:
    - path: LogNiOS
    dependencies:
    - package: LogNCoreFFI
    - package: App
    - package: PostHog
    info:
      path: LogNiOS/Info.plist
      properties:
        UILaunchScreen: {}
        CFBundleURLTypes:
          - CFBundleURLSchemes:
              - logn
            CFBundleURLName: sh.logn.app

