import LogN
import Serde

func serializeArray<T, S: Serializer>(
    value: [T],
    serializer: S,
    serializeElement: (T, S) throws -> Void
) throws {
    try serializer.serialize_len(value: value.count)
    for item in value {
        try serializeElement(item, serializer)
    }
}

func deserializeArray<T, D: Deserializer>(
    deserializer: D,
    deserializeElement: (D) throws -> T
) throws -> [T] {
    let length = try deserializer.deserialize_len()
    var obj: [T] = []
    for _ in 0..<length {
        obj.append(try deserializeElement(deserializer))
    }
    return obj
}

/// Represents a duration of time, internally stored as nanoseconds
public struct Duration: Hashable, Equatable {
    public var nanos: UInt64

    public init(nanos: UInt64) {
        self.nanos = nanos
    }

    public func serialize<S: Serializer>(serializer: S) throws {
        try serializer.increase_container_depth()
        try serializer.serialize_u64(value: self.nanos)
        try serializer.decrease_container_depth()
    }

    public func bincodeSerialize() throws -> [UInt8] {
        let serializer = BincodeSerializer.init();
        try self.serialize(serializer: serializer)
        return serializer.get_bytes()
    }

    public static func deserialize<D: Deserializer>(deserializer: D) throws -> Duration {
        try deserializer.increase_container_depth()
        let nanos = try deserializer.deserialize_u64()
        try deserializer.decrease_container_depth()
        return Duration(nanos: nanos)
    }

    public static func bincodeDeserialize(input: [UInt8]) throws -> Duration {
        let deserializer = BincodeDeserializer.init(input: input);
        let obj = try deserialize(deserializer: deserializer)
        if deserializer.get_buffer_offset() < input.count {
            throw DeserializationError.invalidInput(issue: "Some input bytes were not read")
        }
        return obj
    }
}

/// An error produced when an HTTP request fails.
/// 
/// Variants fall into two groups:
/// 
/// **Transport errors** — generated by the shell when it cannot complete the HTTP
/// exchange. These cross the FFI boundary and are serialized in the protocol:
/// [`Url`](HttpError::Url), [`Io`](HttpError::Io), [`Timeout`](HttpError::Timeout).
/// 
/// **Processing errors** — generated on the Rust side after a response arrives.
/// These are never serialized or visible to shells:
/// 
/// - [`Http`](HttpError::Http) — produced by `Response::new()` when the server returns
/// a 4xx or 5xx status, and **only** then. At the *protocol* level these arrive as
/// [`HttpResult::Ok`](crate::protocol::HttpResult::Ok); `Response::new()` converts
/// them here, so app code using `crux_http::Result<Response<T>>` will see them as
/// `Err(HttpError::Http { code, .. })` — **never** as `Ok(response)` with an error
/// status.
/// - [`Json`](HttpError::Json) — produced when response body deserialisation fails.
/// - [`BodyAlreadyTaken`](HttpError::BodyAlreadyTaken) — a caller took the response body
/// twice.
/// - [`InvalidStatusCode`](HttpError::InvalidStatusCode) — the shell sent a status that
/// isn't valid HTTP.
/// 
/// # Reading what the server said
/// 
/// Because a rejection arrives as an error rather than a response, everything the server
/// sent with it lives on this type: [`HttpError::body`] and [`HttpError::body_json`] for
/// the body, [`HttpError::header`] and [`HttpError::content_type`] for the headers. No
/// matching on the variant's fields required:
/// 
/// ```
/// # use serde::Deserialize;
/// #[derive(Deserialize)]
/// struct ApiError {
/// error: String,
/// }
/// 
/// // the `crux_http::Result` a feature receives when the server rejects a request
/// let result: crux_http::Result<crux_http::Response<Vec<u8>>> =
/// crux_http::testing::rejection(409, r#"{"error":"that overlaps a booked day"}"#);
/// 
/// let error = result.expect_err("a 409 is never Ok");
/// assert_eq!(error.code(), Some(409));
/// assert_eq!(
/// error.body_json::<ApiError>().unwrap().error,
/// "that overlaps a booked day"
/// );
/// ```
indirect public enum HttpError: Hashable, Equatable {
    /// The request URL could not be parsed.
    case url(String)
    /// An IO error prevented the request from completing.
    case io(String)
    /// The request timed out before a response was received.
    case timeout

    public func serialize<S: Serializer>(serializer: S) throws {
        try serializer.increase_container_depth()
        switch self {
        case .url(let x):
            try serializer.serialize_variant_index(value: 0)
            try serializer.serialize_str(value: x)
        case .io(let x):
            try serializer.serialize_variant_index(value: 1)
            try serializer.serialize_str(value: x)
        case .timeout:
            try serializer.serialize_variant_index(value: 2)
        }
        try serializer.decrease_container_depth()
    }

    public func bincodeSerialize() throws -> [UInt8] {
        let serializer = BincodeSerializer.init();
        try self.serialize(serializer: serializer)
        return serializer.get_bytes()
    }

    public static func deserialize<D: Deserializer>(deserializer: D) throws -> HttpError {
        let index = try deserializer.deserialize_variant_index()
        try deserializer.increase_container_depth()
        switch index {
        case 0:
            let x = try deserializer.deserialize_str()
            try deserializer.decrease_container_depth()
            return .url(x)
        case 1:
            let x = try deserializer.deserialize_str()
            try deserializer.decrease_container_depth()
            return .io(x)
        case 2:
            try deserializer.decrease_container_depth()
            return .timeout
        default: throw DeserializationError.invalidInput(issue: "Unknown variant index for HttpError: \(index)")
        }
    }

    public static func bincodeDeserialize(input: [UInt8]) throws -> HttpError {
        let deserializer = BincodeDeserializer.init(input: input);
        let obj = try deserialize(deserializer: deserializer)
        if deserializer.get_buffer_offset() < input.count {
            throw DeserializationError.invalidInput(issue: "Some input bytes were not read")
        }
        return obj
    }
}

public struct HttpHeader: Hashable, Equatable {
    public var name: String
    public var value: String

    public init(name: String, value: String) {
        self.name = name
        self.value = value
    }

    public func serialize<S: Serializer>(serializer: S) throws {
        try serializer.increase_container_depth()
        try serializer.serialize_str(value: self.name)
        try serializer.serialize_str(value: self.value)
        try serializer.decrease_container_depth()
    }

    public func bincodeSerialize() throws -> [UInt8] {
        let serializer = BincodeSerializer.init();
        try self.serialize(serializer: serializer)
        return serializer.get_bytes()
    }

    public static func deserialize<D: Deserializer>(deserializer: D) throws -> HttpHeader {
        try deserializer.increase_container_depth()
        let name = try deserializer.deserialize_str()
        let value = try deserializer.deserialize_str()
        try deserializer.decrease_container_depth()
        return HttpHeader(name: name, value: value)
    }

    public static func bincodeDeserialize(input: [UInt8]) throws -> HttpHeader {
        let deserializer = BincodeDeserializer.init(input: input);
        let obj = try deserialize(deserializer: deserializer)
        if deserializer.get_buffer_offset() < input.count {
            throw DeserializationError.invalidInput(issue: "Some input bytes were not read")
        }
        return obj
    }
}

/// A raw HTTP request, as sent to the shell over the protocol boundary.
/// 
/// # No header validation
/// 
/// All fields are plain strings. Header names and values are carried as-is with no
/// validation against the HTTP specification. This is intentional: `HttpRequest` is a
/// cross-language data carrier deserialised by Swift, Kotlin, and TypeScript shells;
/// Rust's `http`-crate validation rules cannot be enforced on the other side of that
/// boundary.
/// 
/// **Shell authors must not assume that header names or values are well-formed.**
/// Pass them to your underlying HTTP client as-is — it will apply its own rules.
/// 
/// For the ergonomic Rust-side builder that *does* validate header values (and panics
/// on invalid input), see [`crate::command::RequestBuilder`].
public struct HttpRequest: Hashable, Equatable {
    public var method: String
    public var url: String
    public var headers: [HttpHeader]
    public var body: [UInt8]

    public init(method: String, url: String, headers: [HttpHeader], body: [UInt8]) {
        self.method = method
        self.url = url
        self.headers = headers
        self.body = body
    }

    public func serialize<S: Serializer>(serializer: S) throws {
        try serializer.increase_container_depth()
        try serializer.serialize_str(value: self.method)
        try serializer.serialize_str(value: self.url)
        try serializeArray(value: self.headers, serializer: serializer) { item, serializer in
            try item.serialize(serializer: serializer)
        }
        try serializer.serialize_bytes(value: self.body)
        try serializer.decrease_container_depth()
    }

    public func bincodeSerialize() throws -> [UInt8] {
        let serializer = BincodeSerializer.init();
        try self.serialize(serializer: serializer)
        return serializer.get_bytes()
    }

    public static func deserialize<D: Deserializer>(deserializer: D) throws -> HttpRequest {
        try deserializer.increase_container_depth()
        let method = try deserializer.deserialize_str()
        let url = try deserializer.deserialize_str()
        let headers = try deserializeArray(deserializer: deserializer) { deserializer in
            try HttpHeader.deserialize(deserializer: deserializer)
        }
        let body = try deserializer.deserialize_bytes()
        try deserializer.decrease_container_depth()
        return HttpRequest(method: method, url: url, headers: headers, body: body)
    }

    public static func bincodeDeserialize(input: [UInt8]) throws -> HttpRequest {
        let deserializer = BincodeDeserializer.init(input: input);
        let obj = try deserialize(deserializer: deserializer)
        if deserializer.get_buffer_offset() < input.count {
            throw DeserializationError.invalidInput(issue: "Some input bytes were not read")
        }
        return obj
    }
}

public struct HttpResponse: Hashable, Equatable {
    public var status: UInt16
    public var headers: [HttpHeader]
    public var body: [UInt8]

    public init(status: UInt16, headers: [HttpHeader], body: [UInt8]) {
        self.status = status
        self.headers = headers
        self.body = body
    }

    public func serialize<S: Serializer>(serializer: S) throws {
        try serializer.increase_container_depth()
        try serializer.serialize_u16(value: self.status)
        try serializeArray(value: self.headers, serializer: serializer) { item, serializer in
            try item.serialize(serializer: serializer)
        }
        try serializer.serialize_bytes(value: self.body)
        try serializer.decrease_container_depth()
    }

    public func bincodeSerialize() throws -> [UInt8] {
        let serializer = BincodeSerializer.init();
        try self.serialize(serializer: serializer)
        return serializer.get_bytes()
    }

    public static func deserialize<D: Deserializer>(deserializer: D) throws -> HttpResponse {
        try deserializer.increase_container_depth()
        let status = try deserializer.deserialize_u16()
        let headers = try deserializeArray(deserializer: deserializer) { deserializer in
            try HttpHeader.deserialize(deserializer: deserializer)
        }
        let body = try deserializer.deserialize_bytes()
        try deserializer.decrease_container_depth()
        return HttpResponse(status: status, headers: headers, body: body)
    }

    public static func bincodeDeserialize(input: [UInt8]) throws -> HttpResponse {
        let deserializer = BincodeDeserializer.init(input: input);
        let obj = try deserialize(deserializer: deserializer)
        if deserializer.get_buffer_offset() < input.count {
            throw DeserializationError.invalidInput(issue: "Some input bytes were not read")
        }
        return obj
    }
}

/// The result of an HTTP request, as returned by the shell over the protocol boundary.
/// 
/// # Status codes are not errors
/// 
/// Any completed HTTP exchange — including responses with 4xx or 5xx status codes — is
/// returned as [`HttpResult::Ok`]. Only *transport-level* failures (the shell could not
/// reach the server at all) produce [`HttpResult::Err`].
/// 
/// To act on an error status, inspect [`HttpResponse::status`]:
/// 
/// ```
/// # use crux_http::protocol::{HttpResult, HttpResponse};
/// # use crux_http::HttpError;
/// # fn handle(result: HttpResult) {
/// match result {
/// HttpResult::Ok(response) if response.status == 200 => { /* success */ }
/// HttpResult::Ok(response) if response.status == 404 => { /* not found */ }
/// HttpResult::Ok(response) if response.status >= 500 => { /* server error */ }
/// HttpResult::Ok(_) => { /* other status */ }
/// HttpResult::Err(e) => { /* transport failure: bad URL, IO error, or timeout */ }
/// }
/// # }
/// ```
indirect public enum HttpResult: Hashable, Equatable {
    /// The shell completed the HTTP exchange. The response may carry any status code,
    /// including 4xx and 5xx — inspect [`HttpResponse::status`] to distinguish them.
    case ok(HttpResponse)
    /// The shell could not complete the HTTP exchange due to a transport-level failure.
    /// See [`HttpError`] for the possible causes.
    case err(HttpError)

    public func serialize<S: Serializer>(serializer: S) throws {
        try serializer.increase_container_depth()
        switch self {
        case .ok(let x):
            try serializer.serialize_variant_index(value: 0)
            try x.serialize(serializer: serializer)
        case .err(let x):
            try serializer.serialize_variant_index(value: 1)
            try x.serialize(serializer: serializer)
        }
        try serializer.decrease_container_depth()
    }

    public func bincodeSerialize() throws -> [UInt8] {
        let serializer = BincodeSerializer.init();
        try self.serialize(serializer: serializer)
        return serializer.get_bytes()
    }

    public static func deserialize<D: Deserializer>(deserializer: D) throws -> HttpResult {
        let index = try deserializer.deserialize_variant_index()
        try deserializer.increase_container_depth()
        switch index {
        case 0:
            let x = try HttpResponse.deserialize(deserializer: deserializer)
            try deserializer.decrease_container_depth()
            return .ok(x)
        case 1:
            let x = try HttpError.deserialize(deserializer: deserializer)
            try deserializer.decrease_container_depth()
            return .err(x)
        default: throw DeserializationError.invalidInput(issue: "Unknown variant index for HttpResult: \(index)")
        }
    }

    public static func bincodeDeserialize(input: [UInt8]) throws -> HttpResult {
        let deserializer = BincodeDeserializer.init(input: input);
        let obj = try deserialize(deserializer: deserializer)
        if deserializer.get_buffer_offset() < input.count {
            throw DeserializationError.invalidInput(issue: "Some input bytes were not read")
        }
        return obj
    }
}

/// Represents a point in time (UTC):
/// 
/// - seconds: number of seconds since the Unix epoch (1970-01-01T00:00:00Z)
/// - nanos: number of nanoseconds since the last second
public struct Instant: Hashable, Equatable {
    public var seconds: UInt64
    public var nanos: UInt32

    public init(seconds: UInt64, nanos: UInt32) {
        self.seconds = seconds
        self.nanos = nanos
    }

    public func serialize<S: Serializer>(serializer: S) throws {
        try serializer.increase_container_depth()
        try serializer.serialize_u64(value: self.seconds)
        try serializer.serialize_u32(value: self.nanos)
        try serializer.decrease_container_depth()
    }

    public func bincodeSerialize() throws -> [UInt8] {
        let serializer = BincodeSerializer.init();
        try self.serialize(serializer: serializer)
        return serializer.get_bytes()
    }

    public static func deserialize<D: Deserializer>(deserializer: D) throws -> Instant {
        try deserializer.increase_container_depth()
        let seconds = try deserializer.deserialize_u64()
        let nanos = try deserializer.deserialize_u32()
        try deserializer.decrease_container_depth()
        return Instant(seconds: seconds, nanos: nanos)
    }

    public static func bincodeDeserialize(input: [UInt8]) throws -> Instant {
        let deserializer = BincodeDeserializer.init(input: input);
        let obj = try deserialize(deserializer: deserializer)
        if deserializer.get_buffer_offset() < input.count {
            throw DeserializationError.invalidInput(issue: "Some input bytes were not read")
        }
        return obj
    }
}

/// Error type for `KeyValue` operations
indirect public enum KeyValueError: Hashable, Equatable {
    case io(message: String)
    case timeout
    case cursorNotFound
    case other(message: String)

    public func serialize<S: Serializer>(serializer: S) throws {
        try serializer.increase_container_depth()
        switch self {
        case .io(let message):
            try serializer.serialize_variant_index(value: 0)
            try serializer.serialize_str(value: message)
        case .timeout:
            try serializer.serialize_variant_index(value: 1)
        case .cursorNotFound:
            try serializer.serialize_variant_index(value: 2)
        case .other(let message):
            try serializer.serialize_variant_index(value: 3)
            try serializer.serialize_str(value: message)
        }
        try serializer.decrease_container_depth()
    }

    public func bincodeSerialize() throws -> [UInt8] {
        let serializer = BincodeSerializer.init();
        try self.serialize(serializer: serializer)
        return serializer.get_bytes()
    }

    public static func deserialize<D: Deserializer>(deserializer: D) throws -> KeyValueError {
        let index = try deserializer.deserialize_variant_index()
        try deserializer.increase_container_depth()
        switch index {
        case 0:
            let message = try deserializer.deserialize_str()
            try deserializer.decrease_container_depth()
            return .io(message: message)
        case 1:
            try deserializer.decrease_container_depth()
            return .timeout
        case 2:
            try deserializer.decrease_container_depth()
            return .cursorNotFound
        case 3:
            let message = try deserializer.deserialize_str()
            try deserializer.decrease_container_depth()
            return .other(message: message)
        default: throw DeserializationError.invalidInput(issue: "Unknown variant index for KeyValueError: \(index)")
        }
    }

    public static func bincodeDeserialize(input: [UInt8]) throws -> KeyValueError {
        let deserializer = BincodeDeserializer.init(input: input);
        let obj = try deserialize(deserializer: deserializer)
        if deserializer.get_buffer_offset() < input.count {
            throw DeserializationError.invalidInput(issue: "Some input bytes were not read")
        }
        return obj
    }
}

/// Supported operations
indirect public enum KeyValueOperation: Hashable, Equatable {
    /// Read bytes stored under a key
    case get(key: String)
    /// Write bytes under a key
    case set(key: String, value: [UInt8])
    /// Remove a key and its value
    case delete(key: String)
    /// Test if a key exists
    case exists(key: String)
    case listKeys(prefix: String, cursor: UInt64)

    public func serialize<S: Serializer>(serializer: S) throws {
        try serializer.increase_container_depth()
        switch self {
        case .get(let key):
            try serializer.serialize_variant_index(value: 0)
            try serializer.serialize_str(value: key)
        case .set(let key, let value):
            try serializer.serialize_variant_index(value: 1)
            try serializer.serialize_str(value: key)
            try serializeArray(value: value, serializer: serializer) { item, serializer in
                try serializer.serialize_u8(value: item)
            }
        case .delete(let key):
            try serializer.serialize_variant_index(value: 2)
            try serializer.serialize_str(value: key)
        case .exists(let key):
            try serializer.serialize_variant_index(value: 3)
            try serializer.serialize_str(value: key)
        case .listKeys(let prefix, let cursor):
            try serializer.serialize_variant_index(value: 4)
            try serializer.serialize_str(value: prefix)
            try serializer.serialize_u64(value: cursor)
        }
        try serializer.decrease_container_depth()
    }

    public func bincodeSerialize() throws -> [UInt8] {
        let serializer = BincodeSerializer.init();
        try self.serialize(serializer: serializer)
        return serializer.get_bytes()
    }

    public static func deserialize<D: Deserializer>(deserializer: D) throws -> KeyValueOperation {
        let index = try deserializer.deserialize_variant_index()
        try deserializer.increase_container_depth()
        switch index {
        case 0:
            let key = try deserializer.deserialize_str()
            try deserializer.decrease_container_depth()
            return .get(key: key)
        case 1:
            let key = try deserializer.deserialize_str()
            let value = try deserializeArray(deserializer: deserializer) { deserializer in
                try deserializer.deserialize_u8()
            }
            try deserializer.decrease_container_depth()
            return .set(key: key, value: value)
        case 2:
            let key = try deserializer.deserialize_str()
            try deserializer.decrease_container_depth()
            return .delete(key: key)
        case 3:
            let key = try deserializer.deserialize_str()
            try deserializer.decrease_container_depth()
            return .exists(key: key)
        case 4:
            let prefix = try deserializer.deserialize_str()
            let cursor = try deserializer.deserialize_u64()
            try deserializer.decrease_container_depth()
            return .listKeys(prefix: prefix, cursor: cursor)
        default: throw DeserializationError.invalidInput(issue: "Unknown variant index for KeyValueOperation: \(index)")
        }
    }

    public static func bincodeDeserialize(input: [UInt8]) throws -> KeyValueOperation {
        let deserializer = BincodeDeserializer.init(input: input);
        let obj = try deserialize(deserializer: deserializer)
        if deserializer.get_buffer_offset() < input.count {
            throw DeserializationError.invalidInput(issue: "Some input bytes were not read")
        }
        return obj
    }
}

indirect public enum KeyValueResponse: Hashable, Equatable {
    /// Response to a `KeyValueOperation::Get`,
    /// returning the value stored under the key, which may be empty
    case get(value: Value)
    /// Response to a `KeyValueOperation::Set`,
    /// returning the value that was previously stored under the key, may be empty
    case set(previous: Value)
    /// Response to a `KeyValueOperation::Delete`,
    /// returning the value that was previously stored under the key, may be empty
    case delete(previous: Value)
    /// Response to a `KeyValueOperation::Exists`,
    /// returning whether the key is present in the store
    case exists(isPresent: Bool)
    /// Response to a `KeyValueOperation::ListKeys`,
    /// returning a list of keys that start with the prefix, and a cursor to continue listing
    /// if there are more keys
    /// 
    /// Note: the cursor is 0 if there are no more keys
    case listKeys(keys: [String], nextCursor: UInt64)

    public func serialize<S: Serializer>(serializer: S) throws {
        try serializer.increase_container_depth()
        switch self {
        case .get(let value):
            try serializer.serialize_variant_index(value: 0)
            try value.serialize(serializer: serializer)
        case .set(let previous):
            try serializer.serialize_variant_index(value: 1)
            try previous.serialize(serializer: serializer)
        case .delete(let previous):
            try serializer.serialize_variant_index(value: 2)
            try previous.serialize(serializer: serializer)
        case .exists(let isPresent):
            try serializer.serialize_variant_index(value: 3)
            try serializer.serialize_bool(value: isPresent)
        case .listKeys(let keys, let nextCursor):
            try serializer.serialize_variant_index(value: 4)
            try serializeArray(value: keys, serializer: serializer) { item, serializer in
                try serializer.serialize_str(value: item)
            }
            try serializer.serialize_u64(value: nextCursor)
        }
        try serializer.decrease_container_depth()
    }

    public func bincodeSerialize() throws -> [UInt8] {
        let serializer = BincodeSerializer.init();
        try self.serialize(serializer: serializer)
        return serializer.get_bytes()
    }

    public static func deserialize<D: Deserializer>(deserializer: D) throws -> KeyValueResponse {
        let index = try deserializer.deserialize_variant_index()
        try deserializer.increase_container_depth()
        switch index {
        case 0:
            let value = try Value.deserialize(deserializer: deserializer)
            try deserializer.decrease_container_depth()
            return .get(value: value)
        case 1:
            let previous = try Value.deserialize(deserializer: deserializer)
            try deserializer.decrease_container_depth()
            return .set(previous: previous)
        case 2:
            let previous = try Value.deserialize(deserializer: deserializer)
            try deserializer.decrease_container_depth()
            return .delete(previous: previous)
        case 3:
            let isPresent = try deserializer.deserialize_bool()
            try deserializer.decrease_container_depth()
            return .exists(isPresent: isPresent)
        case 4:
            let keys = try deserializeArray(deserializer: deserializer) { deserializer in
                try deserializer.deserialize_str()
            }
            let nextCursor = try deserializer.deserialize_u64()
            try deserializer.decrease_container_depth()
            return .listKeys(keys: keys, nextCursor: nextCursor)
        default: throw DeserializationError.invalidInput(issue: "Unknown variant index for KeyValueResponse: \(index)")
        }
    }

    public static func bincodeDeserialize(input: [UInt8]) throws -> KeyValueResponse {
        let deserializer = BincodeDeserializer.init(input: input);
        let obj = try deserialize(deserializer: deserializer)
        if deserializer.get_buffer_offset() < input.count {
            throw DeserializationError.invalidInput(issue: "Some input bytes were not read")
        }
        return obj
    }
}

/// The result of an operation on the store.
/// 
/// Note: we can't use [`core::result::Result`] here because it is not currently
/// supported across the FFI boundary, when using `typegen` or `facet_typegen`.
indirect public enum KeyValueResult: Hashable, Equatable {
    case ok(response: KeyValueResponse)
    case err(error: KeyValueError)

    public func serialize<S: Serializer>(serializer: S) throws {
        try serializer.increase_container_depth()
        switch self {
        case .ok(let response):
            try serializer.serialize_variant_index(value: 0)
            try response.serialize(serializer: serializer)
        case .err(let error):
            try serializer.serialize_variant_index(value: 1)
            try error.serialize(serializer: serializer)
        }
        try serializer.decrease_container_depth()
    }

    public func bincodeSerialize() throws -> [UInt8] {
        let serializer = BincodeSerializer.init();
        try self.serialize(serializer: serializer)
        return serializer.get_bytes()
    }

    public static func deserialize<D: Deserializer>(deserializer: D) throws -> KeyValueResult {
        let index = try deserializer.deserialize_variant_index()
        try deserializer.increase_container_depth()
        switch index {
        case 0:
            let response = try KeyValueResponse.deserialize(deserializer: deserializer)
            try deserializer.decrease_container_depth()
            return .ok(response: response)
        case 1:
            let error = try KeyValueError.deserialize(deserializer: deserializer)
            try deserializer.decrease_container_depth()
            return .err(error: error)
        default: throw DeserializationError.invalidInput(issue: "Unknown variant index for KeyValueResult: \(index)")
        }
    }

    public static func bincodeDeserialize(input: [UInt8]) throws -> KeyValueResult {
        let deserializer = BincodeDeserializer.init(input: input);
        let obj = try deserialize(deserializer: deserializer)
        if deserializer.get_buffer_offset() < input.count {
            throw DeserializationError.invalidInput(issue: "Some input bytes were not read")
        }
        return obj
    }
}

/// The single operation `Render` implements.
public struct RenderOperation: Hashable, Equatable {
    public init() {
    }

    public func serialize<S: Serializer>(serializer: S) throws {
        try serializer.increase_container_depth()
        try serializer.decrease_container_depth()
    }

    public func bincodeSerialize() throws -> [UInt8] {
        let serializer = BincodeSerializer.init();
        try self.serialize(serializer: serializer)
        return serializer.get_bytes()
    }

    public static func deserialize<D: Deserializer>(deserializer: D) throws -> RenderOperation {
        try deserializer.increase_container_depth()
        try deserializer.decrease_container_depth()
        return RenderOperation()
    }

    public static func bincodeDeserialize(input: [UInt8]) throws -> RenderOperation {
        let deserializer = BincodeDeserializer.init(input: input);
        let obj = try deserialize(deserializer: deserializer)
        if deserializer.get_buffer_offset() < input.count {
            throw DeserializationError.invalidInput(issue: "Some input bytes were not read")
        }
        return obj
    }
}

/// Request for a side-effect passed from the Core to the Shell.
/// 
/// The `EffectId` links the `Request` with the corresponding call to [`Core::resolve`] to pass the data back
/// to the [`App::update`] function (wrapped in the event provided to the capability originating the effect).
public struct Request: Hashable, Equatable {
    public var id: UInt32
    public var effect: LogN.Effect

    public init(id: UInt32, effect: LogN.Effect) {
        self.id = id
        self.effect = effect
    }

    public func serialize<S: Serializer>(serializer: S) throws {
        try serializer.increase_container_depth()
        try serializer.serialize_u32(value: self.id)
        try self.effect.serialize(serializer: serializer)
        try serializer.decrease_container_depth()
    }

    public func bincodeSerialize() throws -> [UInt8] {
        let serializer = BincodeSerializer.init();
        try self.serialize(serializer: serializer)
        return serializer.get_bytes()
    }

    public static func deserialize<D: Deserializer>(deserializer: D) throws -> Request {
        try deserializer.increase_container_depth()
        let id = try deserializer.deserialize_u32()
        let effect = try LogN.Effect.deserialize(deserializer: deserializer)
        try deserializer.decrease_container_depth()
        return Request(id: id, effect: effect)
    }

    public static func bincodeDeserialize(input: [UInt8]) throws -> Request {
        let deserializer = BincodeDeserializer.init(input: input);
        let obj = try deserialize(deserializer: deserializer)
        if deserializer.get_buffer_offset() < input.count {
            throw DeserializationError.invalidInput(issue: "Some input bytes were not read")
        }
        return obj
    }
}

/// A batch of effect requests from the Core to the Shell, as serialised by
/// [`Bridge::update`] and [`Bridge::resolve`].
/// 
/// The wire format is identical to `Vec<Request<Eff>>` (the newtype is
/// `serde(transparent)`), so existing shell code that already deserialises
/// a `Vec<Request>` remains binary-compatible.
/// 
/// Registering this type with the type-generation system causes the code
/// generators to emit a `Requests` type (with a `value` field containing the
/// list) together with a top-level `bincodeDeserialize` / `BincodeDeserialize`
/// helper, replacing the hand-written extension files that were previously
/// appended by `add_extensions()`.
public struct Requests: Hashable, Equatable {
    public var value: [Request]

    public init(value: [Request]) {
        self.value = value
    }

    public func serialize<S: Serializer>(serializer: S) throws {
        try serializer.increase_container_depth()
        try serializeArray(value: self.value, serializer: serializer) { item, serializer in
            try item.serialize(serializer: serializer)
        }
        try serializer.decrease_container_depth()
    }

    public func bincodeSerialize() throws -> [UInt8] {
        let serializer = BincodeSerializer.init();
        try self.serialize(serializer: serializer)
        return serializer.get_bytes()
    }

    public static func deserialize<D: Deserializer>(deserializer: D) throws -> Requests {
        try deserializer.increase_container_depth()
        let value = try deserializeArray(deserializer: deserializer) { deserializer in
            try Request.deserialize(deserializer: deserializer)
        }
        try deserializer.decrease_container_depth()
        return Requests(value: value)
    }

    public static func bincodeDeserialize(input: [UInt8]) throws -> Requests {
        let deserializer = BincodeDeserializer.init(input: input);
        let obj = try deserialize(deserializer: deserializer)
        if deserializer.get_buffer_offset() < input.count {
            throw DeserializationError.invalidInput(issue: "Some input bytes were not read")
        }
        return obj
    }
}

indirect public enum TimeRequest: Hashable, Equatable {
    case now
    case notifyAt(id: TimerId, instant: Instant)
    case notifyAfter(id: TimerId, duration: Duration)
    case clear(id: TimerId)

    public func serialize<S: Serializer>(serializer: S) throws {
        try serializer.increase_container_depth()
        switch self {
        case .now:
            try serializer.serialize_variant_index(value: 0)
        case .notifyAt(let id, let instant):
            try serializer.serialize_variant_index(value: 1)
            try id.serialize(serializer: serializer)
            try instant.serialize(serializer: serializer)
        case .notifyAfter(let id, let duration):
            try serializer.serialize_variant_index(value: 2)
            try id.serialize(serializer: serializer)
            try duration.serialize(serializer: serializer)
        case .clear(let id):
            try serializer.serialize_variant_index(value: 3)
            try id.serialize(serializer: serializer)
        }
        try serializer.decrease_container_depth()
    }

    public func bincodeSerialize() throws -> [UInt8] {
        let serializer = BincodeSerializer.init();
        try self.serialize(serializer: serializer)
        return serializer.get_bytes()
    }

    public static func deserialize<D: Deserializer>(deserializer: D) throws -> TimeRequest {
        let index = try deserializer.deserialize_variant_index()
        try deserializer.increase_container_depth()
        switch index {
        case 0:
            try deserializer.decrease_container_depth()
            return .now
        case 1:
            let id = try TimerId.deserialize(deserializer: deserializer)
            let instant = try Instant.deserialize(deserializer: deserializer)
            try deserializer.decrease_container_depth()
            return .notifyAt(id: id, instant: instant)
        case 2:
            let id = try TimerId.deserialize(deserializer: deserializer)
            let duration = try Duration.deserialize(deserializer: deserializer)
            try deserializer.decrease_container_depth()
            return .notifyAfter(id: id, duration: duration)
        case 3:
            let id = try TimerId.deserialize(deserializer: deserializer)
            try deserializer.decrease_container_depth()
            return .clear(id: id)
        default: throw DeserializationError.invalidInput(issue: "Unknown variant index for TimeRequest: \(index)")
        }
    }

    public static func bincodeDeserialize(input: [UInt8]) throws -> TimeRequest {
        let deserializer = BincodeDeserializer.init(input: input);
        let obj = try deserialize(deserializer: deserializer)
        if deserializer.get_buffer_offset() < input.count {
            throw DeserializationError.invalidInput(issue: "Some input bytes were not read")
        }
        return obj
    }
}

indirect public enum TimeResponse: Hashable, Equatable {
    case now(instant: Instant)
    case instantArrived(id: TimerId)
    case durationElapsed(id: TimerId)
    case cleared(id: TimerId)

    public func serialize<S: Serializer>(serializer: S) throws {
        try serializer.increase_container_depth()
        switch self {
        case .now(let instant):
            try serializer.serialize_variant_index(value: 0)
            try instant.serialize(serializer: serializer)
        case .instantArrived(let id):
            try serializer.serialize_variant_index(value: 1)
            try id.serialize(serializer: serializer)
        case .durationElapsed(let id):
            try serializer.serialize_variant_index(value: 2)
            try id.serialize(serializer: serializer)
        case .cleared(let id):
            try serializer.serialize_variant_index(value: 3)
            try id.serialize(serializer: serializer)
        }
        try serializer.decrease_container_depth()
    }

    public func bincodeSerialize() throws -> [UInt8] {
        let serializer = BincodeSerializer.init();
        try self.serialize(serializer: serializer)
        return serializer.get_bytes()
    }

    public static func deserialize<D: Deserializer>(deserializer: D) throws -> TimeResponse {
        let index = try deserializer.deserialize_variant_index()
        try deserializer.increase_container_depth()
        switch index {
        case 0:
            let instant = try Instant.deserialize(deserializer: deserializer)
            try deserializer.decrease_container_depth()
            return .now(instant: instant)
        case 1:
            let id = try TimerId.deserialize(deserializer: deserializer)
            try deserializer.decrease_container_depth()
            return .instantArrived(id: id)
        case 2:
            let id = try TimerId.deserialize(deserializer: deserializer)
            try deserializer.decrease_container_depth()
            return .durationElapsed(id: id)
        case 3:
            let id = try TimerId.deserialize(deserializer: deserializer)
            try deserializer.decrease_container_depth()
            return .cleared(id: id)
        default: throw DeserializationError.invalidInput(issue: "Unknown variant index for TimeResponse: \(index)")
        }
    }

    public static func bincodeDeserialize(input: [UInt8]) throws -> TimeResponse {
        let deserializer = BincodeDeserializer.init(input: input);
        let obj = try deserialize(deserializer: deserializer)
        if deserializer.get_buffer_offset() < input.count {
            throw DeserializationError.invalidInput(issue: "Some input bytes were not read")
        }
        return obj
    }
}

public struct TimerId: Hashable, Equatable {
    public var value: UInt64

    public init(value: UInt64) {
        self.value = value
    }

    public func serialize<S: Serializer>(serializer: S) throws {
        try serializer.increase_container_depth()
        try serializer.serialize_u64(value: self.value)
        try serializer.decrease_container_depth()
    }

    public func bincodeSerialize() throws -> [UInt8] {
        let serializer = BincodeSerializer.init();
        try self.serialize(serializer: serializer)
        return serializer.get_bytes()
    }

    public static func deserialize<D: Deserializer>(deserializer: D) throws -> TimerId {
        try deserializer.increase_container_depth()
        let value = try deserializer.deserialize_u64()
        try deserializer.decrease_container_depth()
        return TimerId(value: value)
    }

    public static func bincodeDeserialize(input: [UInt8]) throws -> TimerId {
        let deserializer = BincodeDeserializer.init(input: input);
        let obj = try deserialize(deserializer: deserializer)
        if deserializer.get_buffer_offset() < input.count {
            throw DeserializationError.invalidInput(issue: "Some input bytes were not read")
        }
        return obj
    }
}

/// The value stored under a key.
/// 
/// `Value::None` is used to represent the absence of a value.
/// 
/// Note: we can't use `Option` here because generics are not currently
/// supported across the FFI boundary, when using the builtin typegen.
indirect public enum Value: Hashable, Equatable {
    case none
    case bytes([UInt8])

    public func serialize<S: Serializer>(serializer: S) throws {
        try serializer.increase_container_depth()
        switch self {
        case .none:
            try serializer.serialize_variant_index(value: 0)
        case .bytes(let x):
            try serializer.serialize_variant_index(value: 1)
            try serializeArray(value: x, serializer: serializer) { item, serializer in
                try serializer.serialize_u8(value: item)
            }
        }
        try serializer.decrease_container_depth()
    }

    public func bincodeSerialize() throws -> [UInt8] {
        let serializer = BincodeSerializer.init();
        try self.serialize(serializer: serializer)
        return serializer.get_bytes()
    }

    public static func deserialize<D: Deserializer>(deserializer: D) throws -> Value {
        let index = try deserializer.deserialize_variant_index()
        try deserializer.increase_container_depth()
        switch index {
        case 0:
            try deserializer.decrease_container_depth()
            return .none
        case 1:
            let x = try deserializeArray(deserializer: deserializer) { deserializer in
                try deserializer.deserialize_u8()
            }
            try deserializer.decrease_container_depth()
            return .bytes(x)
        default: throw DeserializationError.invalidInput(issue: "Unknown variant index for Value: \(index)")
        }
    }

    public static func bincodeDeserialize(input: [UInt8]) throws -> Value {
        let deserializer = BincodeDeserializer.init(input: input);
        let obj = try deserialize(deserializer: deserializer)
        if deserializer.get_buffer_offset() < input.count {
            throw DeserializationError.invalidInput(issue: "Some input bytes were not read")
        }
        return obj
    }
}
